In [34]:
#Project 1: EIA Data Sets > Total Energy > Environment > Carbon Dioxide Emissions From Energy Consumption: Residential Sector

# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import json
from tqdm import tqdm_notebook
from datetime import datetime
from pprint import pprint

# Import API key
from api_keys_res import api_key

In [35]:
#http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=TOTAL.CLRCEUS.A
#http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=TOTAL.DFRCEUS.A
#http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=TOTAL.HLRCEUS.A
#http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=TOTAL.KSRCEUS.A
#http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=TOTAL.NNRCEUS.A
#http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=TOTAL.PARCEUS.A
#http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=TOTAL.ESRCEUS.A
#http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=TOTAL.TERCEUS.A



url = "http://api.eia.gov/series/?api_key="
api_code1 = "&series_id=TOTAL."
#api_energy_source = "TERCBUS"
api_period = ".A"    


energy_source = [
    "Coal",
    "Distillate Fuel Oil",
    "HGL",
    "Kerosene",
    "Natural Gas, Excluding Supplemental Gaseous Fuel",
    "Petroleum",
    "Residential Share of Electric Power",
    "Total Energy",
]


energy_source_code = [

    "CLRCEUS",
    "DFRCEUS",
    "HLRCEUS",
    "KSRCEUS",
    "NNRCEUS",
    "PARCEUS",
    "ESRCEUS",
    "TERCEUS",
]

energy_source_df = pd.DataFrame({
    "code": energy_source_code,  
    "source": energy_source,
      
})
energy_source_df

      code                                            source
0  CLRCEUS                                              Coal
1  DFRCEUS                               Distillate Fuel Oil
2  HLRCEUS                                               HGL
3  KSRCEUS                                          Kerosene
4  NNRCEUS  Natural Gas, Excluding Supplemental Gaseous Fuel
5  PARCEUS                                         Petroleum
6  ESRCEUS               Residential Share of Electric Power
7  TERCEUS                                      Total Energy

In [36]:
start = []
end = []
f = []
name = []
sector = []
sec = "Residental"
code = []
source = []
series_id = []
units = []
updated = []
year = []
value = []
count_st = 0


for energy in energy_source_df["code"]:
    query_url = url + api_key + api_code1 + energy + api_period
    consume_res_resp = requests.get(query_url).json()

    print("Processing " + energy)
    
    data = []
    data.append(consume_res_resp["series"][0]["data"])
    ln = (len(data[0]))

    for i in range(0, ln):

        start.append(consume_res_resp["series"][0]["start"])
        end.append(consume_res_resp["series"][0]["end"])
        f.append(consume_res_resp["series"][0]["f"])
        name.append(consume_res_resp["series"][0]["name"])
        code.append(consume_res_resp["series"][0]["series_id"].split(".")[1])
        source.append("")
        sector.append(sec)
        series_id.append(consume_res_resp["series"][0]["series_id"])
        units.append(consume_res_resp["series"][0]["units"])
        updated.append(consume_res_resp["series"][0]["updated"])
        year.append(consume_res_resp["series"][0]["data"][i][0])
        value.append(consume_res_resp["series"][0]["data"][i][1])
        
print("-----------------------------")
print("Data Retrieval Complete")      
print("-----------------------------")

Processing CLRCEUS
Processing DFRCEUS
Processing HLRCEUS
Processing KSRCEUS
Processing NNRCEUS
Processing PARCEUS
Processing ESRCEUS
Processing TERCEUS
-----------------------------
Data Retrieval Complete
-----------------------------

In [37]:
#Create DataFrame
emissions_by_source_data = pd.DataFrame({
    "start": start,
    "end": end,
    "f": f,
    "name": name,
    "code": code,
    #"source": source,
    "sector": sector,
    "series_id": series_id,
    "units": units,
    "updated": updated,
    "year": year,
    "value": value
    
})
emissions_by_source_data

,start,end,f,name,code,sector,series_id,units,updated,year,value
0,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2018,NA
1,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2017,NA
2,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2016,NA
3,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2015,NA
4,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2014,NA
5,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2013,NA
6,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2012,NA
7,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2011,NA
8,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2010,NA
9,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2009,NA
10,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2008,NA
11,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2007,0.74
12,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2006,0.618
13,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2005,0.807
14,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2004,1.086
15,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2003,1.169
16,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2002,1.167
17,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2001,1.141
18,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2000,1.083
19,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1999,1.332
20,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1998,1.104
21,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1997,1.519
22,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1996,1.583
23,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1995,1.672
24,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1994,1.995
25,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1993,2.47
26,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1992,2.476
27,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1991,2.443
28,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1990,2.989
29,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1989,2.913
...,...,...,...,...,...,...,...,...,...,...,...
338,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,2002,1202.56
339,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,2001,1171.45
340,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,2000,1185.03
341,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1999,1121.58
342,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1998,1097.4
343,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1997,1089.78
344,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1996,1099.08
345,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1995,1039.04
346,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1994,1032.22
347,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1993,1039.3
348,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1992,981.421
349,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1991,980.095
350,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1990,963.149
351,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1989,1005.13
352,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1988,982.372
353,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1987,934.221
354,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1986,904.915
355,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1985,908.647
356,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1984,902.12
357,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1983,866.888
358,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1982,872.63
359,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1981,878.414
360,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1980,911.355
361,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1979,918.004
362,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1978,938.386
363,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1977,934.507
364,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1976,912.634
365,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1975,867.233
366,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1974,873.107
367,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1973,906.93

In [38]:
emissions_by_source_df = pd.merge(emissions_by_source_data, energy_source_df, on="code")

In [39]:
emissions_by_source_df

,start,end,f,name,code,sector,series_id,units,updated,year,value,source
0,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2018,NA,Coal
1,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2017,NA,Coal
2,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2016,NA,Coal
3,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2015,NA,Coal
4,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2014,NA,Coal
5,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2013,NA,Coal
6,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2012,NA,Coal
7,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2011,NA,Coal
8,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2010,NA,Coal
9,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2009,NA,Coal
10,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2008,NA,Coal
11,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2007,0.74,Coal
12,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2006,0.618,Coal
13,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2005,0.807,Coal
14,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2004,1.086,Coal
15,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2003,1.169,Coal
16,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2002,1.167,Coal
17,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2001,1.141,Coal
18,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2000,1.083,Coal
19,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1999,1.332,Coal
20,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1998,1.104,Coal
21,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1997,1.519,Coal
22,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1996,1.583,Coal
23,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1995,1.672,Coal
24,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1994,1.995,Coal
25,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1993,2.47,Coal
26,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1992,2.476,Coal
27,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1991,2.443,Coal
28,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1990,2.989,Coal
29,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,1989,2.913,Coal
...,...,...,...,...,...,...,...,...,...,...,...,...
338,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,2002,1202.56,Total Energy
339,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,2001,1171.45,Total Energy
340,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,2000,1185.03,Total Energy
341,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1999,1121.58,Total Energy
342,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1998,1097.4,Total Energy
343,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1997,1089.78,Total Energy
344,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1996,1099.08,Total Energy
345,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1995,1039.04,Total Energy
346,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1994,1032.22,Total Energy
347,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1993,1039.3,Total Energy
348,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1992,981.421,Total Energy
349,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1991,980.095,Total Energy
350,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1990,963.149,Total Energy
351,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1989,1005.13,Total Energy
352,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1988,982.372,Total Energy
353,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1987,934.221,Total Energy
354,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1986,904.915,Total Energy
355,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1985,908.647,Total Energy
356,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1984,902.12,Total Energy
357,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1983,866.888,Total Energy
358,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1982,872.63,Total Energy
359,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1981,878.414,Total Energy
360,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1980,911.355,Total Energy
361,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1979,918.004,Total Energy
362,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1978,938.386,Total Energy
363,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1977,934.507,Total Energy
364,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1976,912.634,Total Energy
365,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1975,867.233,Total Energy
366,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1974,873.107,Total Energy
367,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1973,906.93,Total Energy

In [40]:
emissions_by_source_df.head()

,start,end,f,name,code,sector,series_id,units,updated,year,value,source
0,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2018,NA,Coal
1,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2017,NA,Coal
2,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2016,NA,Coal
3,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2015,NA,Coal
4,1973,2018,A,"Coal Residential Sector CO2 Emissions, Annual",CLRCEUS,Residental,TOTAL.CLRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-03-25T14:55:14-0400,2014,NA,Coal

In [41]:
emissions_by_source_df.tail()

,start,end,f,name,code,sector,series_id,units,updated,year,value,source
363,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1977,934.507,Total Energy
364,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1976,912.634,Total Energy
365,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1975,867.233,Total Energy
366,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1974,873.107,Total Energy
367,1973,2018,A,"Total Energy Residential Sector CO2 Emissions,...",TERCEUS,Residental,TOTAL.TERCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1973,906.93,Total Energy

In [44]:
emissions_by_source_df[150:250]

,start,end,f,name,code,sector,series_id,units,updated,year,value,source
150,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,2006,4.798,Kerosene
151,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,2005,6.06,Kerosene
152,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,2004,6.129,Kerosene
153,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,2003,5.083,Kerosene
154,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,2002,4.334,Kerosene
155,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,2001,6.875,Kerosene
156,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,2000,6.838,Kerosene
157,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1999,8.038,Kerosene
158,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1998,7.832,Kerosene
159,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1997,6.716,Kerosene
160,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1996,6.419,Kerosene
161,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1995,5.372,Kerosene
162,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1994,4.694,Kerosene
163,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1993,5.467,Kerosene
164,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1992,4.7,Kerosene
165,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1991,5.231,Kerosene
166,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1990,4.621,Kerosene
167,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1989,8.48,Kerosene
168,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1988,10.379,Kerosene
169,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1987,8.585,Kerosene
170,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1986,8.772,Kerosene
171,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1985,11.462,Kerosene
172,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1984,11.59,Kerosene
173,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1983,6.174,Kerosene
174,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1982,6.876,Kerosene
175,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1981,6.171,Kerosene
176,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1980,7.71,Kerosene
177,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1979,9.604,Kerosene
178,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1978,11.052,Kerosene
179,1973,2018,A,"Kerosene Residential Sector CO2 Emissions, Annual",KSRCEUS,Residental,TOTAL.KSRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-04-25T08:13:40-0400,1977,12.102,Kerosene
...,...,...,...,...,...,...,...,...,...,...,...,...
220,1973,2018,A,"Natural Gas, Excluding Supplemental Gaseous Fu...",NNRCEUS,Residental,TOTAL.NNRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1982,249.963,"Natural Gas, Excluding Supplemental Gaseous Fuel"
221,1973,2018,A,"Natural Gas, Excluding Supplemental Gaseous Fu...",NNRCEUS,Residental,TOTAL.NNRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1981,244.814,"Natural Gas, Excluding Supplemental Gaseous Fuel"
222,1973,2018,A,"Natural Gas, Excluding Supplemental Gaseous Fu...",NNRCEUS,Residental,TOTAL.NNRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1980,255.99,"Natural Gas, Excluding Supplemental Gaseous Fuel"
223,1973,2018,A,"Natural Gas, Excluding Supplemental Gaseous Fu...",NNRCEUS,Residental,TOTAL.NNRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1979,268.188,"Natural Gas, Excluding Supplemental Gaseous Fuel"
224,1973,2018,A,"Natural Gas, Excluding Supplemental Gaseous Fu...",NNRCEUS,Residental,TOTAL.NNRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1978,264.299,"Natural Gas, Excluding Supplemental Gaseous Fuel"
225,1973,2018,A,"Natural Gas, Excluding Supplemental Gaseous Fu...",NNRCEUS,Residental,TOTAL.NNRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1977,260.672,"Natural Gas, Excluding Supplemental Gaseous Fuel"
226,1973,2018,A,"Natural Gas, Excluding Supplemental Gaseous Fu...",NNRCEUS,Residental,TOTAL.NNRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1976,273.1,"Natural Gas, Excluding Supplemental Gaseous Fuel"
227,1973,2018,A,"Natural Gas, Excluding Supplemental Gaseous Fu...",NNRCEUS,Residental,TOTAL.NNRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1975,266.483,"Natural Gas, Excluding Supplemental Gaseous Fuel"
228,1973,2018,A,"Natural Gas, Excluding Supplemental Gaseous Fu...",NNRCEUS,Residental,TOTAL.NNRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1974,260.03,"Natural Gas, Excluding Supplemental Gaseous Fuel"
229,1973,2018,A,"Natural Gas, Excluding Supplemental Gaseous Fu...",NNRCEUS,Residental,TOTAL.NNRCEUS.A,Million Metric Tons of Carbon Dioxide,2019-06-24T11:59:37-0400,1973,264.062,"Natural Gas, Excluding Supplemental Gaseous Fuel"
230,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2018,64.269,Petroleum
231,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2017,59.366,Petroleum
232,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2016,59.867,Petroleum
233,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2015,69.136,Petroleum
234,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2014,70.817,Petroleum
235,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2013,65.74,Petroleum
236,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2012,60.758,Petroleum
237,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2011,70.604,Petroleum
238,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2010,76.552,Petroleum
239,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2009,79.093,Petroleum
240,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2008,91.247,Petroleum
241,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2007,86.419,Petroleum
242,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2006,84.79,Petroleum
243,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2005,100.814,Petroleum
244,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2004,105.899,Petroleum
245,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2003,107.533,Petroleum
246,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2002,101.045,Petroleum
247,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2001,106.406,Petroleum
248,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,2000,107.954,Petroleum
249,1973,2018,A,"Petroleum Residential Sector CO2 Emissions, An...",PARCEUS,Residental,TOTAL.PARCEUS.A,Million Metric Tons of Carbon Dioxide,2019-05-23T15:52:44-0400,1999,101.7,Petroleum