In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import json
import requests
from pprint import pprint

# Import API key
from api_keys import api_key

In [2]:
url = "http://api.eia.gov/series/?api_key="
api_code1 = "&series_id=EMISS.CO2-TOTV-TC-TO-"
api_code2 = ".A"

state_abb = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
           "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
           "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
           "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
           "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

In [3]:
start = []
end = []
f = []
geo = []
state = []
name = []
sector = []
series_id = []
source = []
units = []
units_short = []
updated = []
year = []
emission = []
data = []
count_st = 0

for st in state_abb:
        query_url = url + api_key + api_code1 + st + api_code2
        count_st = count_st + 1
        print("Processing Record " + str(count_st) + " | " + st)

        emiss_response = requests.get(query_url).json()
        
       
        data.append(emiss_response["series"][0]["data"])
        ln = (len(data[0]))

        for i in range(0,ln):
            start.append(emiss_response["series"][0]["start"])
            end.append(emiss_response["series"][0]["end"])
            f.append(emiss_response["series"][0]["f"])
            geo.append(emiss_response["series"][0]["geography"])
            state.append(emiss_response["series"][0]["geography"].split("-")[1])
            name.append(emiss_response["series"][0]["name"])
            sector.append(emiss_response["series"][0]["name"].split(" ")[0])
            series_id.append(emiss_response["series"][0]["series_id"])
            source.append(emiss_response["series"][0]["source"])
            units.append(emiss_response["series"][0]["units"])
            units_short.append(emiss_response["series"][0]["unitsshort"])
            updated.append(emiss_response["series"][0]["updated"])
            year.append(emiss_response["series"][0]["data"][i][0])
            emission.append(emiss_response["series"][0]["data"][i][1])
print("-----------------------------")
print("Data Retrieval Complete")
print("-----------------------------")

Processing Record 1 | AL
Processing Record 2 | AK
Processing Record 3 | AZ
Processing Record 4 | AR
Processing Record 5 | CA
Processing Record 6 | CO
Processing Record 7 | CT
Processing Record 8 | DE
Processing Record 9 | FL
Processing Record 10 | GA
Processing Record 11 | HI
Processing Record 12 | ID
Processing Record 13 | IL
Processing Record 14 | IN
Processing Record 15 | IA
Processing Record 16 | KS
Processing Record 17 | KY
Processing Record 18 | LA
Processing Record 19 | ME
Processing Record 20 | MD
Processing Record 21 | MA
Processing Record 22 | MI
Processing Record 23 | MN
Processing Record 24 | MS
Processing Record 25 | MO
Processing Record 26 | MT
Processing Record 27 | NE
Processing Record 28 | NV
Processing Record 29 | NH
Processing Record 30 | NJ
Processing Record 31 | NM
Processing Record 32 | NY
Processing Record 33 | NC
Processing Record 34 | ND
Processing Record 35 | OH
Processing Record 36 | OK
Processing Record 37 | OR
Processing Record 38 | PA
Processing Record 39 | RI
Processing Record 40 | SC
Processing Record 41 | SD
Processing Record 42 | TN
Processing Record 43 | TX
Processing Record 44 | UT
Processing Record 45 | VT
Processing Record 46 | VA
Processing Record 47 | WA
Processing Record 48 | WV
Processing Record 49 | WI
Processing Record 50 | WY
-----------------------------
Data Retrieval Complete
-----------------------------

In [4]:
# create dataframe
emiss_trans_df = pd.DataFrame({
   "start":start,
   "end":end,
   "geo": geo,
   "state": state,
   "name": name,
   "sector": sector,
   "series_id": series_id,
   "source": source,
   "units": units,
   "units_short": units_short,
   "updated": updated,
   "year": year,
   "emission": emission
})

emiss_trans_df['year'] = emiss_trans_df['year'].astype(int)
emiss_trans_df

,start,end,geo,state,name,sector,series_id,source,units,units_short,updated,year,emission
0,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2016,34.693718
1,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2015,32.907554
2,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2014,31.596261
3,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2013,31.586515
4,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2012,31.824413
5,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2011,32.296325
6,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2010,32.236319
7,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2009,31.935441
8,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2008,32.964470
9,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2007,35.632563
10,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2006,35.290356
11,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2005,34.712625
12,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2004,34.838696
13,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2003,32.299034
14,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2002,33.385752
15,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2001,31.362301
16,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2000,33.430379
17,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1999,31.989275
18,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1998,31.618369
19,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1997,31.050595
20,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1996,31.428589
21,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1995,32.073149
22,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1994,30.570768
23,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1993,29.375693
24,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1992,29.337850
25,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1991,28.640832
26,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1990,28.038790
27,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1989,28.255392
28,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1988,26.322502
29,1980,2016,USA-AL,AL,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-AL.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1987,25.989983
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1820,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2009,8.168505
1821,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2008,8.518022
1822,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2007,8.741162
1823,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2006,8.521520
1824,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2005,8.261602
1825,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2004,8.042668
1826,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2003,8.442046
1827,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2002,7.647417
1828,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2001,7.702690
1829,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,2000,7.541893
1830,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1999,8.018708
1831,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1998,7.029550
1832,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1997,6.826518
1833,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1996,6.715423
1834,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1995,6.712691
1835,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1994,5.800478
1836,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1993,5.904245
1837,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1992,5.524554
1838,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1991,5.252092
1839,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1990,5.716457
1840,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1989,5.953555
1841,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1988,5.878852
1842,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1987,5.421486
1843,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1986,4.453408
1844,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1985,4.814085
1845,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1984,4.767822
1846,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1983,4.677085
1847,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1982,5.565859
1848,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1981,6.231095
1849,1980,2016,USA-WY,WY,"Transportation carbon dioxide emissions, all f...",Transportation,EMISS.CO2-TOTV-TC-TO-WY.A,"EIA, U.S. Energy Information Administration",million metric tons CO2,mmt CO2,2018-12-12T09:19:26-0500,1980,6.221419

In [5]:
emiss_bystate = emiss_trans_df.groupby(["state", "sector"])

tot_emissions = emiss_bystate["emission"].sum()

bystate_df = pd.DataFrame({"Total Emissions": tot_emissions})

bystate_df

                      Total Emissions
state sector
AK    Transportation       468.819019
AL    Transportation      1114.876551
AR    Transportation       665.058793
AZ    Transportation      1035.661981
CA    Transportation      7380.431552
CO    Transportation       884.594634
CT    Transportation       568.906519
DE    Transportation       168.515910
FL    Transportation      3336.182932
GA    Transportation      2018.567811
HI    Transportation       370.807764
IA    Transportation       676.663709
ID    Transportation       284.109801
IL    Transportation      2232.574521
IN    Transportation      1514.814348
KS    Transportation       687.183539
KY    Transportation      1068.911852
LA    Transportation      1849.097727
MA    Transportation      1091.138542
MD    Transportation       984.383943
ME    Transportation       291.955411
MI    Transportation      1846.868935
MN    Transportation      1078.506852
MO    Transportation      1357.718992
MS    Transportation       852.423246
MT    Transportation       258.787253
NC    Transportation      1623.302542
ND    Transportation       221.077957
NE    Transportation       432.395778
NH    Transportation       225.900082
NJ    Transportation      2210.024616
NM    Transportation       509.865423
NV    Transportation       454.396183
NY    Transportation      2446.936211
OH    Transportation      2271.764055
OK    Transportation      1022.955262
OR    Transportation       769.006919
PA    Transportation      2312.325537
RI    Transportation       153.473796
SC    Transportation       935.467304
SD    Transportation       202.228056
TN    Transportation      1389.207495
TX    Transportation      6375.885404
UT    Transportation       503.327814
VA    Transportation      1650.258747
VT    Transportation       121.238026
WA    Transportation      1487.104715
WI    Transportation       994.627335
WV    Transportation       417.086065
WY    Transportation       254.234001

In [6]:
emiss_10years = emiss_trans_df.set_index("state","sector").groupby(["state","sector"])

tot_10emissions = emiss_trans_df[emiss_trans_df["year"] >= 2006].groupby(["state","sector"])["emission"].sum()

rec10yrs_df = pd.DataFrame({"Total Emissions": tot_10emissions})

rec10yrs_df

                      Total Emissions
state sector
AK    Transportation       155.879984
AL    Transportation       362.963935
AR    Transportation       214.817759
AZ    Transportation       362.842585
CA    Transportation      2326.274608
CO    Transportation       316.404622
CT    Transportation       174.238441
DE    Transportation        49.989526
FL    Transportation      1146.952326
GA    Transportation       665.548507
HI    Transportation       115.527057
IA    Transportation       229.219550
ID    Transportation       102.459751
IL    Transportation       738.328867
IN    Transportation       469.256088
KS    Transportation       209.737742
KY    Transportation       350.065160
LA    Transportation       528.101202
MA    Transportation       338.039758
MD    Transportation       321.828777
ME    Transportation        94.482270
MI    Transportation       547.355772
MN    Transportation       352.288390
MO    Transportation       425.775813
MS    Transportation       283.667772
MT    Transportation        88.438517
NC    Transportation       542.412232
ND    Transportation        85.727793
NE    Transportation       145.189513
NH    Transportation        75.954795
NJ    Transportation       691.455871
NM    Transportation       155.872225
NV    Transportation       164.737088
NY    Transportation       785.158286
OH    Transportation       715.185804
OK    Transportation       346.445394
OR    Transportation       238.323429
PA    Transportation       704.321511
RI    Transportation        44.938027
SC    Transportation       340.241501
SD    Transportation        70.741665
TN    Transportation       466.426027
TX    Transportation      2220.771560
UT    Transportation       187.601691
VA    Transportation       553.889026
VT    Transportation        38.093213
WA    Transportation       474.225091
WI    Transportation       322.526627
WV    Transportation       126.315958
WY    Transportation        89.110303