In [10]:
# Dependencies
import requests
import csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# import api_key from config file
from config import eia_key
from pprint import pprint

# CO2 Emission by State - Annual

In [11]:
series_url = "http://api.eia.gov/series/?" + "api_key=" + eia_key + "&series_id="

state_abbr = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
           "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
           "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
           "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
           "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
emission_state_pre = "EMISS.CO2-TOTV-IC-TO-"
emission_state_post = ".A"

header_df = pd.DataFrame()
# # set up additional columns to hold header information
header_df["pk_id"] = ""
header_df["sector"] = ""
header_df["energy_source"] = ""
header_df["frequency"] = ""
header_df["name"] = ""
header_df["source"] = ""
header_df["series_id"] = ""
header_df["unit_long"] = ""
header_df["unit_short"] = ""
header_df["state"] = ""
header_df["data_for"] = ""

line_df = pd.DataFrame()
# # set up additional columns to hold line information
line_df["fk_id"] = ""
line_df["year"] = ""
line_df["month"] = ""
line_df["value"] = ""


for count, st in enumerate(state_abbr, start=1):
    query_url = series_url + emission_state_pre + st + emission_state_post
    st_co2_json = requests.get(query_url).json()
    header_df = header_df.append({"pk_id" : count,
                                  "sector" : st_co2_json["series"][0]['name'].split(" ")[0],
                                  "name" : st_co2_json["series"][0]['name'],
                                  "source" : st_co2_json["series"][0]['source'],
                                  "frequency" : "Annual",
                                  "series_id" : st_co2_json["series"][0]['series_id'], 
                                  "unit_long" : st_co2_json["series"][0]['units'],
                                  "unit_short" : st_co2_json["series"][0]['unitsshort'],
                                  "state" : st_co2_json["series"][0]['geography'].split("-")[1],
                                  "data_for" : "CO2-Emission-By-State",
                                 } , ignore_index=True )
    
    for dt in st_co2_json["series"][0]["data"]:
            line_df = line_df.append({"fk_id" : count,
                              "year" : dt[0],
                              "month" : 13,
                              "value" : dt[1]        
                               } , ignore_index=True )
    pkid = count
    
print("-----------------------------")
print("Data Retrieval Complete for CO2 Emission by State")
print("-----------------------------")

-----------------------------
Data Retrieval Complete for CO2 Emission by State
-----------------------------

In [8]:
# header_df

In [9]:
# line_df

# CO2 Emission - Annual

In [12]:
emission_pre = "TOTAL."
emission_post = ".A"
energy_source = ["CLICEUS", "DFICEUS", "HLICEUS", "KSICEUS", 
                "LUICEUS", "MMICEUS", "NNICEUS", "OPICEUS",
                "PCICEUS", "PMICEUS", "RFICEUS", "TEICEUS"]

for count, es in enumerate(energy_source, start=pkid+1):
    query_url = series_url + emission_pre + es + emission_post
    co2_json = requests.get(query_url).json()
    header_df = header_df.append({"pk_id" : count,
                                  "sector" : "Industrial",
                                  "energy_source" : co2_json["series"][0]['name'].split(" ")[0],
                                  "frequency" : "Annual",
                                  "name" : co2_json["series"][0]['name'],
                                  "source" : "EIA, U.S. Energy Information Administration",
                                  "series_id" : co2_json["series"][0]['series_id'], 
                                  "unit_long" : co2_json["series"][0]['units'],
                                  "data_for" : "CO2-Emission",
                                 } , ignore_index=True )
    
    for dt in co2_json["series"][0]["data"]:
            line_df = line_df.append({"fk_id" : count,
                                      "year" : dt[0],
                                      "month" : 13,
                                      "value" : dt[1]
                               } , ignore_index=True )
    pkid = count
    
print("-----------------------------")
print("Data Retrieval Complete for CO2 Emission")
print("-----------------------------")

-----------------------------
Data Retrieval Complete for CO2 Emission
-----------------------------

# Energy Consumption - Annual

In [13]:
consumption_pre = "TOTAL."
consumption_post = ".A"
consumption_source = ["TEICBUS", "WYICBUS", "CLICBUS", "HVICBUS",
                      "GEICBUS", "NNICBUS", "PMICBUS", "SOICBUS"]

for count, cs in enumerate(consumption_source, start=pkid+1):
    query_url = series_url + consumption_pre + cs + consumption_post
    cons_json = requests.get(query_url).json()
    header_df = header_df.append({"pk_id" : count,
                                  "sector" : "Industrial",
                                  "energy_source" : cons_json["series"][0]['name'].split(" ")[0],
                                  "frequency" : "Annual",
                                  "name" : cons_json["series"][0]['name'],
                                  "source" : "EIA, U.S. Energy Information Administration",
                                  "series_id" : cons_json["series"][0]['series_id'], 
                                  "unit_long" : cons_json["series"][0]['units'],
                                  "data_for" : "Consumption",
                                 } , ignore_index=True )
    
    for dt in cons_json["series"][0]["data"]:
            line_df = line_df.append({"fk_id" : count,
                                      "year" : dt[0],
                                      "month" : 13,
                                      "value" : dt[1]
                               } , ignore_index=True )
    pkid = count
    
print("-----------------------------")
print("Data Retrieval Complete for Consumption")
print("-----------------------------")

-----------------------------
Data Retrieval Complete for Consumption
-----------------------------

In [14]:
header_df

,pk_id,sector,energy_source,frequency,name,source,series_id,unit_long,unit_short,state,data_for
0,1,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-AL.A,million metric tons CO2,mmt CO2,AL,CO2-Emission-By-State
1,2,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-AK.A,million metric tons CO2,mmt CO2,AK,CO2-Emission-By-State
2,3,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-AZ.A,million metric tons CO2,mmt CO2,AZ,CO2-Emission-By-State
3,4,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-AR.A,million metric tons CO2,mmt CO2,AR,CO2-Emission-By-State
4,5,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-CA.A,million metric tons CO2,mmt CO2,CA,CO2-Emission-By-State
5,6,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-CO.A,million metric tons CO2,mmt CO2,CO,CO2-Emission-By-State
6,7,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-CT.A,million metric tons CO2,mmt CO2,CT,CO2-Emission-By-State
7,8,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-DE.A,million metric tons CO2,mmt CO2,DE,CO2-Emission-By-State
8,9,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-FL.A,million metric tons CO2,mmt CO2,FL,CO2-Emission-By-State
9,10,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-GA.A,million metric tons CO2,mmt CO2,GA,CO2-Emission-By-State
10,11,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-HI.A,million metric tons CO2,mmt CO2,HI,CO2-Emission-By-State
11,12,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-ID.A,million metric tons CO2,mmt CO2,ID,CO2-Emission-By-State
12,13,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-IL.A,million metric tons CO2,mmt CO2,IL,CO2-Emission-By-State
13,14,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-IN.A,million metric tons CO2,mmt CO2,IN,CO2-Emission-By-State
14,15,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-IA.A,million metric tons CO2,mmt CO2,IA,CO2-Emission-By-State
15,16,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-KS.A,million metric tons CO2,mmt CO2,KS,CO2-Emission-By-State
16,17,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-KY.A,million metric tons CO2,mmt CO2,KY,CO2-Emission-By-State
17,18,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-LA.A,million metric tons CO2,mmt CO2,LA,CO2-Emission-By-State
18,19,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-ME.A,million metric tons CO2,mmt CO2,ME,CO2-Emission-By-State
19,20,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-MD.A,million metric tons CO2,mmt CO2,MD,CO2-Emission-By-State
20,21,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-MA.A,million metric tons CO2,mmt CO2,MA,CO2-Emission-By-State
21,22,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-MI.A,million metric tons CO2,mmt CO2,MI,CO2-Emission-By-State
22,23,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-MN.A,million metric tons CO2,mmt CO2,MN,CO2-Emission-By-State
23,24,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-MS.A,million metric tons CO2,mmt CO2,MS,CO2-Emission-By-State
24,25,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-MO.A,million metric tons CO2,mmt CO2,MO,CO2-Emission-By-State
25,26,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-MT.A,million metric tons CO2,mmt CO2,MT,CO2-Emission-By-State
26,27,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-NE.A,million metric tons CO2,mmt CO2,NE,CO2-Emission-By-State
27,28,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-NV.A,million metric tons CO2,mmt CO2,NV,CO2-Emission-By-State
28,29,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-NH.A,million metric tons CO2,mmt CO2,NH,CO2-Emission-By-State
29,30,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-NJ.A,million metric tons CO2,mmt CO2,NJ,CO2-Emission-By-State
...,...,...,...,...,...,...,...,...,...,...,...
40,41,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-SD.A,million metric tons CO2,mmt CO2,SD,CO2-Emission-By-State
41,42,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-TN.A,million metric tons CO2,mmt CO2,TN,CO2-Emission-By-State
42,43,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-TX.A,million metric tons CO2,mmt CO2,TX,CO2-Emission-By-State
43,44,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-UT.A,million metric tons CO2,mmt CO2,UT,CO2-Emission-By-State
44,45,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-VT.A,million metric tons CO2,mmt CO2,VT,CO2-Emission-By-State
45,46,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-VA.A,million metric tons CO2,mmt CO2,VA,CO2-Emission-By-State
46,47,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-WA.A,million metric tons CO2,mmt CO2,WA,CO2-Emission-By-State
47,48,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-WV.A,million metric tons CO2,mmt CO2,WV,CO2-Emission-By-State
48,49,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-WI.A,million metric tons CO2,mmt CO2,WI,CO2-Emission-By-State
49,50,Industrial,NaN,Annual,"Industrial carbon dioxide emissions, all fuels...","EIA, U.S. Energy Information Administration",EMISS.CO2-TOTV-IC-TO-WY.A,million metric tons CO2,mmt CO2,WY,CO2-Emission-By-State
50,51,Industrial,Coal,Annual,"Coal Industrial Sector CO2 Emissions, Annual","EIA, U.S. Energy Information Administration",TOTAL.CLICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
51,52,Industrial,Distillate,Annual,Distillate Fuel Oil Industrial Sector CO2 Emis...,"EIA, U.S. Energy Information Administration",TOTAL.DFICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
52,53,Industrial,HGL,Annual,"HGL Industrial Sector CO2 Emissions, Annual","EIA, U.S. Energy Information Administration",TOTAL.HLICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
53,54,Industrial,Kerosene,Annual,"Kerosene Industrial Sector CO2 Emissions, Annual","EIA, U.S. Energy Information Administration",TOTAL.KSICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
54,55,Industrial,Lubricants,Annual,"Lubricants Industrial Sector CO2 Emissions, An...","EIA, U.S. Energy Information Administration",TOTAL.LUICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
55,56,Industrial,Motor,Annual,"Motor Gasoline, Excluding Ethanol, Industrial ...","EIA, U.S. Energy Information Administration",TOTAL.MMICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
56,57,Industrial,Natural,Annual,"Natural Gas Industrial Sector CO2 Emissions, A...","EIA, U.S. Energy Information Administration",TOTAL.NNICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
57,58,Industrial,Other,Annual,Other Petroleum Products Industrial Sector CO2...,"EIA, U.S. Energy Information Administration",TOTAL.OPICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
58,59,Industrial,Petroleum,Annual,Petroleum Coke Industrial Sector CO2 Emissions...,"EIA, U.S. Energy Information Administration",TOTAL.PCICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
59,60,Industrial,"Petroleum,",Annual,"Petroleum, Excluding Biofuels, Industrial Sect...","EIA, U.S. Energy Information Administration",TOTAL.PMICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
60,61,Industrial,Residual,Annual,Residual Fuel Oil Industrial Sector CO2 Emissi...,"EIA, U.S. Energy Information Administration",TOTAL.RFICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
61,62,Industrial,Total,Annual,"Total Industrial Sector CO2 Emissions, Annual","EIA, U.S. Energy Information Administration",TOTAL.TEICEUS.A,Million Metric Tons of Carbon Dioxide,NaN,NaN,CO2-Emission
62,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption
63,64,Industrial,Wind,Annual,"Wind Energy Consumed by the Industrial Sector,...","EIA, U.S. Energy Information Administration",TOTAL.WYICBUS.A,Trillion Btu,NaN,NaN,Consumption
64,65,Industrial,Coal,Annual,"Coal Consumed by the Industrial Sector, Annual","EIA, U.S. Energy Information Administration",TOTAL.CLICBUS.A,Trillion Btu,NaN,NaN,Consumption
65,66,Industrial,Conventional,Annual,Conventional Hydroelectric Power Consumed by t...,"EIA, U.S. Energy Information Administration",TOTAL.HVICBUS.A,Trillion Btu,NaN,NaN,Consumption
66,67,Industrial,Geothermal,Annual,Geothermal Energy Consumed by the Industrial S...,"EIA, U.S. Energy Information Administration",TOTAL.GEICBUS.A,Trillion Btu,NaN,NaN,Consumption
67,68,Industrial,Natural,Annual,Natural Gas Consumed by the Industrial Sector ...,"EIA, U.S. Energy Information Administration",TOTAL.NNICBUS.A,Trillion Btu,NaN,NaN,Consumption
68,69,Industrial,Petroleum,Annual,Petroleum Consumed by the Industrial Sector (E...,"EIA, U.S. Energy Information Administration",TOTAL.PMICBUS.A,Trillion Btu,NaN,NaN,Consumption
69,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption

In [15]:
line_df

     fk_id  year month    value
0        1  2016    13  21.0648
1        1  2015    13  21.0093
2        1  2014    13  22.1458
3        1  2013    13  21.0848
4        1  2012    13  21.3822
5        1  2011    13  19.2796
6        1  2010    13  18.8499
7        1  2009    13     17.4
8        1  2008    13  21.1118
9        1  2007    13  21.5405
10       1  2006    13  22.1399
11       1  2005    13  22.7146
12       1  2004    13  24.0695
13       1  2003    13  23.7108
14       1  2002    13  22.4731
15       1  2001    13  22.6534
16       1  2000    13  26.1491
17       1  1999    13  26.8136
18       1  1998    13  26.4855
19       1  1997    13  29.0377
20       1  1996    13  29.9015
21       1  1995    13  29.0924
22       1  1994    13  28.3536
23       1  1993    13  27.3784
24       1  1992    13  28.6933
25       1  1991    13  25.7855
26       1  1990    13  25.4993
27       1  1989    13  25.4183
28       1  1988    13   26.259
29       1  1987    13  23.7944
...    ...   ...   ...      ...
2932    70  1978    13       NA
2933    70  1977    13       NA
2934    70  1976    13       NA
2935    70  1975    13       NA
2936    70  1974    13       NA
2937    70  1973    13       NA
2938    70  1972    13       NA
2939    70  1971    13       NA
2940    70  1970    13       NA
2941    70  1969    13       NA
2942    70  1968    13       NA
2943    70  1967    13       NA
2944    70  1966    13       NA
2945    70  1965    13       NA
2946    70  1964    13       NA
2947    70  1963    13       NA
2948    70  1962    13       NA
2949    70  1961    13       NA
2950    70  1960    13       NA
2951    70  1959    13       NA
2952    70  1958    13       NA
2953    70  1957    13       NA
2954    70  1956    13       NA
2955    70  1955    13       NA
2956    70  1954    13       NA
2957    70  1953    13       NA
2958    70  1952    13       NA
2959    70  1951    13       NA
2960    70  1950    13       NA
2961    70  1949    13       NA

[2962 rows x 4 columns]

In [22]:
# header_df.head(100)
header_df.to_csv("Header.csv")

header_df["pk_id"] = pd.to_numeric(header_df["pk_id"])
header_df.dtypes

pk_id             int64
sector           object
energy_source    object
frequency        object
name             object
source           object
series_id        object
unit_long        object
unit_short       object
state            object
data_for         object
dtype: object

In [23]:
# line_df
line_df.to_csv("Line.csv")

line_df["fk_id"] = pd.to_numeric(line_df["fk_id"])
line_df["year"] = pd.to_numeric(line_df["year"])
line_df["month"] = pd.to_numeric(line_df["month"])

line_df.loc[line_df["value"] == 'NA', ["value"] ] = np.NaN
line_df.loc[line_df["value"] == '-', ["value"] ] = np.NaN
line_df["value"] = line_df["value"].astype(float)
line_df.dtypes

c:\users\shahz\appdata\local\programs\python\python37\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

fk_id      int64
year       int64
month      int64
value    float64
dtype: object

In [24]:
# header_df.reset_index()
# line_df.reset_index()
# header_line_df = pd.merge(header_df, line_df, how="left", on=["pk_id", "fk_id"], right_index=True).fillna(0)

header_line_df = pd.merge(header_df, line_df, how='inner', left_on="pk_id", right_on="fk_id")
header_line_df

header_line_df.to_csv("HeaderLine.csv")

In [33]:
header_line_df.dtypes

pk_id              int64
sector            object
energy_source     object
frequency         object
name              object
source            object
series_id         object
unit_long         object
unit_short        object
state             object
data_for          object
fk_id              int64
year               int64
month              int64
value            float64
dtype: object

In [41]:

yearly_consumption_df = header_line_df[header_line_df["data_for"]=="Consumption"]
yearly_emission_df = header_line_df[header_line_df["data_for"] == "CO2-Emission"]
yearly_emission_state_df = header_line_df[header_line_df["data_for"] == "CO2-Emission-By-State"]

In [42]:
yearly_consumption_df

,pk_id,sector,energy_source,frequency,name,source,series_id,unit_long,unit_short,state,data_for,fk_id,year,month,value
2402,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2018,13,32617.767
2403,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2017,13,32005.673
2404,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2016,13,31452.839
2405,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2015,13,31471.524
2406,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2014,13,31797.941
2407,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2013,13,31627.437
2408,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2012,13,31060.724
2409,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2011,13,30981.322
2410,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2010,13,30670.436
2411,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2009,13,28465.439
2412,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2008,13,31333.358
2413,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2007,13,32384.515
2414,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2006,13,32390.355
2415,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2005,13,32441.115
2416,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2004,13,33515.280
2417,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2003,13,32552.715
2418,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2002,13,32660.366
2419,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2001,13,32718.499
2420,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,2000,13,34662.130
2421,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1999,13,34762.524
2422,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1998,13,34841.110
2423,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1997,13,35198.990
2424,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1996,13,34902.978
2425,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1995,13,33969.227
2426,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1994,13,33519.691
2427,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1993,13,32618.544
2428,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1992,13,32570.887
2429,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1991,13,31399.342
2430,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1990,13,31801.602
2431,63,Industrial,Total,Annual,Total Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.TEICBUS.A,Trillion Btu,NaN,NaN,Consumption,63,1989,13,31327.767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2932,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1978,13,NaN
2933,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1977,13,NaN
2934,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1976,13,NaN
2935,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1975,13,NaN
2936,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1974,13,NaN
2937,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1973,13,NaN
2938,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1972,13,NaN
2939,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1971,13,NaN
2940,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1970,13,NaN
2941,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1969,13,NaN
2942,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1968,13,NaN
2943,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1967,13,NaN
2944,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1966,13,NaN
2945,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1965,13,NaN
2946,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1964,13,NaN
2947,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1963,13,NaN
2948,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1962,13,NaN
2949,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1961,13,NaN
2950,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1960,13,NaN
2951,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1959,13,NaN
2952,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1958,13,NaN
2953,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1957,13,NaN
2954,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1956,13,NaN
2955,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1955,13,NaN
2956,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1954,13,NaN
2957,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1953,13,NaN
2958,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1952,13,NaN
2959,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1951,13,NaN
2960,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1950,13,NaN
2961,70,Industrial,Solar,Annual,Solar Energy Consumed by the Industrial Sector...,"EIA, U.S. Energy Information Administration",TOTAL.SOICBUS.A,Trillion Btu,NaN,NaN,Consumption,70,1949,13,NaN